library(e1071)
data <- read.csv("C:\\Users\\Ala\\PycharmProjects\\dswp\\Statystyka\\7.10\\napoje_po_reklamie.csv", sep=";")

print("Mean:")
print(lapply(data[,-1],mean))
print("Max:")
print(lapply(data[,-1],max))
print("Min:")
print(lapply(data[,-1],min))
print("Min:")
print(lapply(data[,-1],min))
print("Sd:")
print(lapply(data[,-1],sd))
print("Var:")
print(lapply(data[,-1],var))
print("Kurtosis:")
print(lapply(data[,-1],kurtosis))
print("Skewness:")
print(lapply(data[,-1],skewness))